<?php


$title = "Modifier mon profil";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$numAdmission = $form->get('admission_number');
$numAdmission->setAttribute('class', 'form-control');
$numAdmission->setAttribute('placeholder', 'numero admission');

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Nom');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('student_students', [
    'action' => 'edit',
    'id'     => $admission_number,
]));

$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($numAdmission, "Numéro d'admission") ?>
    <?= $this->formElement($numAdmission) ?>
    <?= $this->formElementErrors()->render($numAdmission, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($name, 'Nom') ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>


<a class="btn btn-primary" href="<?= $this->url('student_file')?>">Ajouter un CV à votre profil</a>

<?php
echo $this->formSubmit($submit);
//echo $this->formHidden($form->get('user_id'));
echo $this->form()->closeTag();
