<?php


$title = 'NOTIFIONS CE Boi.';
$url   = $this->url('employer_StudentsInternships', ['action' => 'notifier', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Voulez-vous vraiment le notifier ?

</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $id ?>" />
    <input type="submit" class="btn btn-success" name="del" value="Yes" />
    <input type="submit" class="btn btn-danger" name="del" value="No" />
</div>
</form>