<?php


$title = "Ajouter les informations d'un etudiant";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$numAdmission = $form->get('admission_number');
$numAdmission->setAttribute('class', 'form-control');
$numAdmission->setAttribute('placeholder', 'numero admission');

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Nom');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Courriel');

$active = $form->get('active');
$active->setAttribute('class', 'form-check-input');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'mot de passe');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('students', [
    'action' => 'add'
]));

$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($numAdmission, "Numéro d'admission") ?>
    <?= $this->formElement($numAdmission) ?>
    <?= $this->formElementErrors()->render($numAdmission, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($name, "Nom") ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($email, "Courriel") ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($password, "Mot de passe") ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($active, "Actif") ?>
    <?= $this->formElement($active) ?>
    <?= $this->formElementErrors()->render($active, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();