<?php


$title = 'Supprimer un etudiant';
$url   = $this->url('students', ['action' => 'delete', 'id' => $admission_number]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Voulez-vous vraiment supprimer cet etudiant?
    <?= $this->escapeHtml($student->admission_number) ?>
    <?= $this->escapeHtml($student->name) ?>
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="admission_number" value="<?= (int) $student->admission_number ?>" />
    <input type="submit" class="btn btn-primary" name="del" value="Oui" />
    <input type="submit" class="btn btn-primary" name="del" value="Non" />
</div>
</form>