<?php


$title = "Modifier les informations d'un etudiant";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$numAdmission = $form->get('numero_admission');
$numAdmission->setAttribute('class', 'form-control');
$numAdmission->setAttribute('placeholder', 'numero admission');

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Nom');

$active = $form->get('active');
$active->setAttribute('class', 'form-control');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('student', [
    'action' => 'edit',
    'id'     => $numAdmission,
]));

$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($numAdmission) ?>
    <?= $this->formElement($numAdmission) ?>
    <?= $this->formElementErrors()->render($numAdmission, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($active) ?>
    <?= $this->formElement($active) ?>
    <?= $this->formElementErrors()->render($active, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('user_id'));
echo $this->form()->closeTag();