<?php

$title = 'Étudiants';
$this->headTitle($title);
?>

<h1 class="page-header"><?= $title?></h1>

<a href="<?= $this->url('students', ['action' => 'add']) ?>"><i class="glyphicon glyphicon-plus"></i> Ajouter</a>
<table class="table">
<tr>
    <th>Numéro d'admission</th>
    <th>Nom</th>
    <th>Est actif</th>
    <th>Actions</th>
</tr>
<?php foreach ($students as $student) : ?>
    <tr>
        <td><?= $this->escapeHtml($student->admission_number) ?></td>
        <td><?= $this->escapeHtml($student->name) ?></td>
        <td><?= $this->escapeHtml($student->active) ?></td>
        <td>
            <a href="<?= $this->url('students', ['action' => 'edit', 'id' => $student->admission_number]) ?>">Modifier</a>
            <a href="<?= $this->url('students', ['action' => 'delete', 'id' => $student->admission_number]) ?>">Supprimer</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>