<h1><?php echo $this->escapeHtml($internship->name);?></h1>

<p>Date postée : <?php echo $this->escapeHtml($internship->date_posted);?></p>
<p>Active : <?php echo $this->escapeHtml($internship->active);?></p>
<p>Employeur : <?php echo $this->escapeHtml($internship->active);?></p> <!-- Lien vers l'employeur sans un controller ? -->
<p>Description : </p>
<p><?php echo $this->escapeHtml($internship->description);?></p>
