<?php


$title = 'Supprimer un employeur';
$url   = $this->url('employers', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Voulez-vous vraiment supprimer cet employeur?
    <?= $this->escapeHtml($employer->id) ?>
    <?= $this->escapeHtml($employer->name) ?>
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $employer->id ?>" />
    <input type="submit" class="btn btn-primary" name="del" value="Yes" />
    <input type="submit" class="btn btn-primary" name="del" value="No" />
</div>
</form>