<?php

$title = "Modifier un employeur";
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$id = $form->get('id');
$id->setAttribute('class', 'form-control');
$id->setAttribute('placeholder', 'le id');

$courriel = $form->get('contact_email');
$courriel->setAttribute('class', 'form-control');
$courriel->setAttribute('placeholder', 'courriel de contact');

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Nom');

$adress = $form->get('adress');
$adress->setAttribute('class', 'form-control');
$adress->setAttribute('placeholder', 'Adresse');

$city = $form->get('city');
$city->setAttribute('class', 'form-control');
$city->setAttribute('placeholder', 'ville');

$province = $form->get('province');
$province->setAttribute('class', 'form-control');
$province->setAttribute('placeholder', 'province');

$postal = $form->get('postal_code');
$postal->setAttribute('class', 'form-control');
$postal->setAttribute('placeholder', 'code postal');

$active = $form->get('active');
$active->setAttribute('class', 'form-check-input');

$uuid = $form->get('uuid');
$uuid->setAttribute('class', 'form-check-input');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('employers', [
    'action' => 'add'
]));

$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formElement($id) ?>
        <?= $this->formElementErrors()->render($id, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($name, "Nom") ?>
        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($adress, "Adresse") ?>
        <?= $this->formElement($adress) ?>
        <?= $this->formElementErrors()->render($adress, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($city, "Ville") ?>
        <?= $this->formElement($city) ?>
        <?= $this->formElementErrors()->render($city, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($courriel, "Courriel de contact") ?>
        <?= $this->formElement($courriel) ?>
        <?= $this->formElementErrors()->render($courriel, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($province, "Province") ?>
        <?= $this->formElement($province) ?>
        <?= $this->formElementErrors()->render($province, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($postal, "Code postal") ?>
        <?= $this->formElement($postal) ?>
        <?= $this->formElementErrors()->render($postal, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($active, "Actif") ?>
        <?= $this->formElement($active) ?>
        <?= $this->formElementErrors()->render($active, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formElement($uuid) ?>
        <?= $this->formElementErrors()->render($uuid, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();