<?php

$title = 'Accueil';
$this->headTitle($title);
?>

<h1 class="page-header text-center"><?= $title?></h1>
<div class="row">
    <div class="col-sm-4 col-md-offset-4 text-center">
        
        <div class="panel panel-default">
            <div class="panel-heading ">Stages</div>
            <div class="panel-body">
                <p>Consulter vos stages</p>
            </div>
            <div class="panel-footer">
                <a class="btn btn-primary" href="<?= $this->url('employer_internships') ?>">Consulter</a>
            </div>
        </div>
    </div>   
</div>
<div class="row">
    <div class="col-sm-4 col-md-offset-4 text-center">
        <div class="panel panel-default">
            <div class="panel-heading">Liste des postulants</div>
            <div class="panel-body">
                <p>Consulter la liste des postulants vous concernant</p>
            </div>
            <div class="panel-footer">
                <a class="btn btn-primary" href="<?= $this->url('employer_StudentsInternships')?>">Consulter</a>
            </div>
        </div>
    </div>
</div>
