
  <div class="container">
    <div class="row">
    <div class="col-sm-3 col-md-3 col-lg-3">
    </div>
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Se Connecter</h5>
            <form class="form-signin" action="<?= $this->url('employer_users', ['action' => 'login']);?>" method="post">
              <div class="form-label-group">
                <input name="email" type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
                <label for="email">Courriel</label>
              </div>

              <div class="form-label-group">
                <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                <label for="password">Mot de passe</label>
              </div>


              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Connexion</button>
              
            </form>
            <?php /* a inserer pour iteration 3
            <h5 class="card-title text-center"><a href="<?= $this->url('users', ['action' => 'lostPassword']);?>">Mot de passe oublié?</a></h5> 
            */?>

             <!--<h5 class="card-title text-center"><a href="<?php//= $this->url('users', ['action' => 'lostPassword']);?>">Mot de passe oublié?</a></h5>-->
            <h5 class="card-title text-center"><a href="<?= $this->url('users', ['action' => 'login']);?>">Cliquez ici pour coordonateur</a></h5>
            <h5 class="card-title text-center"><a href="<?= $this->url('student_users', ['action' => 'login']);?>">Cliquez ici pour étudiant</a></h5>
            <hr />
            <a href="<?= $this->url('employer_users', ['action' => 'add']);?>" class="btn btn-lg btn-primary btn-block text-uppercase">S'inscrire</a>
          </div>
        </div>
      </div>
      </div>
    
  </div>
