<?php

$title = "Ajouter un stage";
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$id = $form->get('id');
$id->setAttribute('class', 'form-control');
$id->setAttribute('placeholder', 'le id');

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'nom stage');

$date_posted = $form->get('date_posted');
$date_posted->setAttribute('class', 'form-control');
$date_posted->setAttribute('placeholder', 'Date du postage');

$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'description');

$id_employer = $form->get('id_employer');
$id_employer->setAttribute('class', 'form-control');
$id_employer->setAttribute('placeholder', 'employer id');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('employers', [
    'action' => 'add'
]));

$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($name, "Nom stage") ?>
        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($description, "description") ?>
        <?= $this->formElement($description) ?>
        <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();