<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Gestion Stages')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo16.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-fixed-top" style="background-color: gray" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('employer_home') ?>">
                        <img src="<?= $this->basePath('img/logo72.png') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Gestion Stage | Employeur
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                <?php if($currentUser != null) : ?>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('employer_home') ?>">Accueil</a></li>
                        <li class="active"><a href="<?= $this->url('employer_internships') ?>">Stages</a></li>                      
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active"><a href="<?=$this->url('employer_users', ['action' => 'logout']) ?>">Déconnexion</a></li>
                    </ul>
                    <?php elseif ($currentUser == null): ?>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('student_users', ['action' => 'login']) ?>">Étudiants</a></li>
                        <li class="active"><a href="<?= $this->url('users', ['action' => 'login']) ?>">Coordonnateur</a></li>
                    </ul>
                    <?php endif;?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer class="footer navbar-fixed-bottom" style="background-color: gray">
                <center>
                <p>By Gestion Stage.</p>
                </center>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
