<?php

$title = 'Les offres';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Titre</th>
        <th>Description</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($internships as $internship) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($internship->name);?></td>
            <td><?php echo $this->escapeHtml($internship->description);?></td>
            <td>
                <a href="<?php echo $this->url('internship',
                    array('action'=>'details', 'id' => $internship->id));?>">Détails</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>