<?php

$title = 'Accueil';
$this->headTitle($title);
?>

<h1 class="page-header"><?= $title?></h1>
<div class="row">
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">Étudiants</div>
            <div class="panel-body">
                <p>Consulter la liste des étudiants</p>
            </div>
            <div class="panel-footer">
                <a class="btn btn-primary" href="<?= $this->url('students') ?>">Consulter</a>
            </div>
        </div>
    </div>        
</div>